[package]
name = "gq"
version = "0.1.0"
authors = ["Ben Aubin <ben@benaubin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gq_internals = { path = "../gq_internals" }
gq_macros = { path = "../gq_macros" }